### ISSUE TITLE
Update the github workflow

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#236]
- Currently, the github workflow is not working
- Fix it by inserting the following codes.

````
# This is the work flow to generate preview links for Pull Requests
name: PR-Preview-Generator
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Installing Surge
        run: npm i -g surge
      - name: Deploying on Surge
        env:
          DEPLOY_DOMAIN: https://pr-${{ github.event.number }}-CALCULATOR-WEBSITE.surge.sh
          SURGE_TOKEN: aadbfcb04e3dae63bb3561ca05f93eb1
        run: surge ./ $DEPLOY_DOMAIN --token $SURGE_TOKEN
````
